// packages/react-example/src/routes/Common.tsx
import { useDozerCount, useDozerQuery } from "@dozerjs/dozer-react";
import { Box } from "@mui/material";
import { useContext } from "react";
import { DataTable } from "../components/DataTable";
import { EndpointsContext } from "../contexts/Endpoints";

function Count(props: {
  endpoint: string;
}) {
  const { count, error } = useDozerCount(props.endpoint);
  return error?.message ?? <Box>{count}</Box>;
}

function Records(props: {
  endpoint: string;
}) {
  const { fields, records, error } = useDozerQuery(props.endpoint);
  return <DataTable fields={fields} records={records} error={error}></DataTable>;
}

export function Common() {
  const options = useContext(EndpointsContext);

  return options.map(option => (
    <Box key={option.endpoint}>
      <Box sx={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
        <h3>{option.endpoint}</h3>
        <Count endpoint={option.endpoint} />
      </Box>
      <Records endpoint={option.endpoint} />
    </Box>
  ));
}

// packages/vue-example/src/views/Common.vue
<script setup lang="ts">
import { DozerOnEventOption } from "@dozerjs/dozer";
import { inject } from 'vue';
import Count from '../components/Count.vue';
import Records from '../components/Records.vue';

const options = inject<DozerOnEventOption[]>('endpoints');

</script>

<template>
  <div v-for="option in options">
    <div>
      <div class="count">
        <h3>{{ option.endpoint }}</h3>
        <Count :endpoint="option.endpoint"/>
      </div>
      <Records :endpoint="option.endpoint"/>
    </div>
  </div>
</template>

<style scoped>
.count {
  display: flex;
  gap: 1rem;
  align-items: center;
}
</style>
