// packages/react-example/src/components/ErrorMessage.tsx
import { Alert, Box } from "@mui/material"

export function ErrorMessage(props: {
  error: Error
}) {
  return (
    <Box sx={{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      height: '500px',
    }}>
      <Alert severity="error">{props.error.message}</Alert>
    </Box>
  )
}

// packages/vue-example/src/components/ErrorMessage.vue
<script setup lang="ts">
const { error } = defineProps<{
  error: Error;
}>();
</script>
<template>
  <div class="error-container">
    <v-alert
      color="error"
      variant="tonal"
      :text="error.message"
      class="error-message"
    ></v-alert>
  </div>
</template>

<style scoped>
.error-container {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 500px;
}

.error-message {
  flex: 0 0 auto;
}
</style>
