// packages/react-example/src/components/NavBar.tsx
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Tab from '@mui/material/Tab';
import Tabs from '@mui/material/Tabs';
import Toolbar from '@mui/material/Toolbar';
import * as React from 'react';
import { Link, useLocation } from 'react-router-dom';

export function NavBar() {
  const routes = [
    {
      label: 'Common',
      path: '/',
    },
    {
      label: 'Count + Event',
      path: '/count-event',
    },
    {
      label: 'Query + Event',
      path: '/query-event',
    },
    {
      label: 'Endpoints',
      path: '/endpoints',
    },
  ];
  const location = useLocation();
  const index = routes.findIndex((route) => route.path === location.pathname);

  const [active, setActive] = React.useState<number>(index);


  return (
    <AppBar position="static">
      <Toolbar sx={{ gap: '2rem' }}>
        <img src="/logo.svg" alt="Dozer" width={137} height={40} />
        <Box sx={{ flexGrow: 1, display: 'flex' }}>
          <Tabs value={active} onChange={(_, val) => setActive(val)}>
            {
              routes.map((route) => <Tab key={route.path} component={Link} label={route.label} to={route.path} />)
            }
          </Tabs>
        </Box>
      </Toolbar>
    </AppBar>
  );
}

// packages/vue-example/src/components/NavBar.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRoute } from 'vue-router';
const routes = [
  {
    label: 'Common',
    path: '/',
  },
  {
    label: 'Count + Event',
    path: '/count-event',
  },
  {
    label: 'Query + Event',
    path: '/query-event',
  },
  {
    label: 'Endpoints',
    path: '/endpoints',
  },
];

const route = useRoute();
const index = routes.findIndex(item => item.path === route.path);
const active = ref(index);
</script>

<template>
  <v-toolbar class="toolbar">
    <img src="/logo.svg" alt="Dozer" width="137" height="40" />
    <div class="navs">
      <v-tabs v-model="active">
        <v-tab v-for="route in routes" :value="route.path" :to="route.path">{{ route.label }}</v-tab>
      </v-tabs>
    </div>
  </v-toolbar>
</template>

<style scoped>
.toolbar :deep .v-toolbar__content {
  padding: 0 24px;
  gap: 2rem;
  width: 100%;
}
.navs {
  flex-grow: 1;
  min-width: 0;
  display: flex;
}

.navs :deep .v-tab {
  flex-grow: 1;
  min-width: 0;
  color: #939393;
}

.navs :deep .v-tab--selected {
  color: rgb(var(--v-theme-primary));
}
</style>
