// packages/react-example/src/App.tsx
import { types_pb } from '@dozerjs/dozer';
import { DozerProvider, useDozerWatch } from '@dozerjs/dozer-react';
import { DozerTable } from './DataTable';
import { Box } from '@mui/material';


function Endpoints () {
  const options = [
    {
      endpoint: 'trips_cache',
      eventType: types_pb.EventType.ALL,
    },
  ];

  const { stream } = useDozerWatch(options);

  return (
    <Box sx={{
      display: 'flex',
      flexDirection: 'column',
      gap: '1rem',
    }}>
      {
        options.map(option => <DozerTable key={option.endpoint} stream={stream} endpoint={option.endpoint}/>)
      }
    </Box>
  )
}

function App() {
  return (
    <DozerProvider value={{
      serverAddress: 'http://127.0.0.1:62998'
    }}>
      <Endpoints />
    </DozerProvider>
  )
}

export default App

// packages/vue-example/src/App.vue
<script setup lang="ts">
import { DozerOnEventOption, types_pb } from '@dozerjs/dozer';
import { DozerProvider } from '@dozerjs/dozer-vue';
import { RouterView } from 'vue-router';
import { provide } from 'vue';
import NavBar from './components/NavBar.vue'

provide<DozerOnEventOption[]>('endpoints', [
  {
    endpoint: 'airports_count',
    eventType: types_pb.EventType.ALL,
  },
  {
    endpoint: 'departures_count',
    eventType: types_pb.EventType.ALL,
  },
  {
    endpoint: 'airports',
    eventType: types_pb.EventType.ALL,
  },
]);

</script>

<template>
   <DozerProvider :value="{
      serverAddress: 'http://localhost:62998',
    }">
      <div class="container">
        <NavBar />
        <div class="content">
          <RouterView />
        </div>
      </div>
    </DozerProvider>
</template>

<style scoped>
.container {
  height: 100%;
  display: flex;
  flex-direction: column;
}

.content {
  flex: 1;
  min-height: 0;
  padding: 1.5rem;
}
</style>
