// packages/vue-example/src/views/Endpoints.vue
<script setup lang="ts">
import { DozerOnEventOption } from "@dozerjs/dozer";
import { useDozerEndpoints } from '@dozerjs/dozer-vue';
import { inject } from 'vue';
import DataTable from "../components/DataTable.vue";

const options = inject<DozerOnEventOption[]>('endpoints', []);
const data = useDozerEndpoints(options);
</script>

<template>
  <div v-for="(option, index) in options">
    <div>
      <h3>{{ option.endpoint }}</h3>
      <DataTable :fields="data[index]?.fields ?? []" :records="data[index]?.records ?? []" :error="data[index]?.error"/>
    </div>
  </div>
</template>

// packages/react-example/src/routes/Endpoints.tsx
import { useDozerEndpoints } from "@dozerjs/dozer-react";
import { Box } from "@mui/material";
import { useContext } from "react";
import { DataTable } from "../components/DataTable";
import { EndpointsContext } from "../contexts/Endpoints";

export function Endpoints() {
  const options = useContext(EndpointsContext);

  const data = useDozerEndpoints(options);

  return options.map((option, index) => (
    <Box key={option.endpoint}>
      <h3>{option.endpoint}</h3>
      <DataTable {...data[index]} />
    </Box>
  ));
}
